import Head from 'next/head'
import { Inter } from 'next/font/google'
import Layout from '@/components/Layout'
import profilePic from '../../public/images/profile/My pic.png'
import Image from 'next/image'
import AnimatedText from '@/components/AnimatedText'
import Link from 'next/link'
import { LinkArrow } from '@/components/Icons'
import HireMe from '@/components/HireMe'
import pcImage from '../../public/images/svgs/pc.svg'
import TransitionEffect from '@/components/TransitionEffect'
import ParticlesContainer from '@/components/ParticlesContainer'
const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  return (
    <>
      <Head>
        <title>Imran&#39;s Portfolio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <TransitionEffect />
    <main className='flex items-center text-dark w-full min-h-screen dark:text-light '>
        {/* <Layout className='pt-0 md:p-16 sm:pt-8'>
      <ParticlesContainer />
          <div className="flex lg:flex-col  items-center justify-between w-full">
            <div className='w-1/2 md:w-full sm:-mt-48 sm:mb-3'>
              <Image src={profilePic} alt="Imran" className='w-full h-auto lg:hidden md:inline-block md:w-full z-50'
              priority
              sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
              />
            </div>
            <div className='w-1/2 flex flex-col items-center self-center lg:w-full sm:pt-10 lg:text-center'>
              
              <AnimatedText className='!text-6xl !text-left !tracking-wide
              xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl
              ' text="Hi, I am Imran Ahmed Khan" />
              <p className='font-semibold my-4 text-2xl md:text-sm sm:text-xs'>I am a Full Stack Software Engineer based at Chattogram, Bangladesh. I like turning ideas into innovative software applications.</p>
              <div className='flex items-center self-start lg:self-center mt-2'>
                <Link href="https://drive.google.com/uc?export=download&id=1tGouJfE9XiDqF0VR8wp4aMSQ6IgeaXmA"
                download
                className='flex group items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold
                hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light
                hover:dark:border-light md:p-2 md:px-4 md:text-base'
                >
                  Resume
                  <LinkArrow className={"w-6 ml-1 group-hover:animate-bounce group-hover:pt-1"} />
                </Link>
              </div>
            </div>
          </div>
        </Layout> */}
        <Layout className='pt-0 md:p-16 sm:pt-8'>
  <div className='relative'>
    <ParticlesContainer />
    <div className="flex lg:flex-col items-center justify-between w-full">
      <div className='w-1/2 md:w-full sm:-mt-48 sm:mb-3'>
        <Image
          src={profilePic}
          alt="Imran"
          className='w-full h-auto lg:hidden md:inline-block md:w-full z-50'
          priority
          sizes="(max-width: 768px) 100vw, (max-width: 1200px) 50vw, 50vw"
        />
      </div>
      <div className='w-1/2 flex flex-col items-center self-center lg:w-full sm:pt-10 lg:text-center'>
        <AnimatedText className='!text-6xl !text-left !tracking-wide xl:!text-5xl lg:!text-center lg:!text-6xl md:!text-5xl sm:!text-3xl' text="Hi, I am Imran Ahmed Khan" />
        <p className='font-semibold my-4 text-2xl md:text-sm sm:text-xs'>I am a Full Stack Software Engineer based in Chattogram, Bangladesh. I like turning ideas into innovative software applications.</p>
        <div className='flex items-center self-start lg:self-center mt-2'>
          <Link
            href="https://drive.google.com/uc?export=download&id=1tGouJfE9XiDqF0VR8wp4aMSQ6IgeaXmA"
            download
            className='flex group items-center bg-dark text-light p-2.5 px-6 rounded-lg text-lg font-semibold hover:bg-light hover:text-dark border-2 border-solid border-transparent hover:border-dark dark:bg-light dark:text-dark hover:dark:bg-dark hover:dark:text-light hover:dark:border-light md:p-2 md:px-4 md:text-base'
          >
            Resume
            <LinkArrow className={"w-6 ml-1 group-hover:animate-bounce group-hover:pt-1"} />
          </Link>
        </div>
      </div>
    </div>
  </div>
</Layout>


        <HireMe />
        <div className='absolute right-8 bottom-8 inline-block w-24 hover:animate-pulse md:hidden'>
          <Image src={pcImage} alt='laptop' className='w-full h-auto' />
        </div>
      </main>
    </>
  )
}
